### PR TITLE
[RHMWRT-221] Add OpenShift labels

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by aureamunoz** [comment]
LGTM but why CI is failing?

**Comment by gytis** [comment]
I messed up the `application.yaml` template, CircleCI passes now. As for the `rhoar-bot` I'm not sure in what state it is. Does it ever pass these days? @aureamunoz @geoand

**Comment by geoand** [comment]
Good question, I have no idea TBH

**Comment by aureamunoz** [comment]
No idea either :-/

**Pull request merged**
